name: ShareManager
options:
  bundleIdPrefix: net.fenyo.apple
  deploymentTarget:
    iOS: "17.6"
  developmentLanguage: en
  knownRegions:
    - en
    - en-AU
    - en-CA
    - en-GB
    - ar
    - bn
    - ca
    - cs
    - da
    - de
    - el
    - es
    - es-MX
    - fi
    - fr
    - fr-CA
    - gu
    - he
    - hi
    - hr
    - hu
    - id
    - it
    - ja
    - kn
    - ko
    - ml
    - mr
    - ms
    - nb
    - nl
    - or
    - pa
    - pl
    - pt
    - ro
    - ru
    - sk
    - sl
    - sv
    - ta
    - te
    - th
    - tr
    - uk
    - ur
    - vi
    - zh-Hans
    - zh-Hant

targets:
  ShareManager:
    type: application
    platform: iOS
    deploymentTarget: "17.6"
    sources:
      - path: ShareManager
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.fenyo.apple.sharemanager
        INFOPLIST_FILE: ShareManager/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_ENTITLEMENTS: ShareManager/ShareManager.entitlements
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: ShareExtension
        embed: true
      - target: ShareWidget
        embed: true

  ShareWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.6"
    sources:
      - path: ShareWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.fenyo.apple.sharemanager.sharewidget
        INFOPLIST_FILE: ShareWidget/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_ENTITLEMENTS: ShareWidget/ShareWidget.entitlements
        SWIFT_VERSION: "5.9"

  ShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.6"
    sources:
      - path: ShareExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.fenyo.apple.sharemanager.shareextension
        INFOPLIST_FILE: ShareExtension/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_ENTITLEMENTS: ShareExtension/ShareExtension.entitlements
        SWIFT_VERSION: "5.9"

schemes:
  ShareManager:
    build:
      targets:
        ShareManager: all
        ShareExtension: all
        ShareWidget: all
    run:
      config: Debug
      executable: ShareManager
